name: Staging Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - staging

jobs:
  run-pipeline:
    name: Run pipeline
    uses: ./.github/workflows/ci-pipeline.yml
    secrets: inherit
    permissions:
      id-token: write
      contents: read
    with:
      environment: "staging"
